package tn.taktak.GestCommerciale_V1.entity;

// Generated 23 avr. 2015 18:41:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
//import javax.validation.constraints.Size;

import lombok.Getter;
import lombok.Setter;

/**
 * Article generated by hbm2java
 */
@Entity
@Getter
@Setter
public class Article  {

	@Id
	//@Size(min = 1, message = "Code Article na peut pas etre null!")
	private String carticle;
	//@Size(min = 1, message = "Designation Article na peut pas etre null!")
	private String desArticle;
	//@Size(min = 1, message = "Unite Article na peut pas etre null!")
	private String cunite;
	private String ctva;
	private String codeBarre;
	private boolean fodec;
	private boolean gererStock;
	private boolean droitConsommation;
	private BigDecimal qteStock;
	private BigDecimal prixAchat;
	private BigDecimal prixVente;
	private BigDecimal mtMarge;
	private BigDecimal poidsBrut;
	private BigDecimal poidsNet;
	private String typeCodeBare;
	private String description;

	public Article() {
	}

	public Article(String carticle, String desArticle, String cunite,
			String ctva, boolean fodec, boolean gererStock,
			boolean droitConsommation, BigDecimal prixAchat,
			BigDecimal prixVente) {
		this.carticle = carticle;
		this.desArticle = desArticle;
		this.cunite = cunite;
		this.ctva = ctva;
		this.fodec = fodec;
		this.gererStock = gererStock;
		this.droitConsommation = droitConsommation;
		this.prixAchat = prixAchat;
		this.prixVente = prixVente;
		
	}

	public Article(String carticle, String desArticle, String cunite,
			String ctva, String codeBarre, boolean fodec, boolean gererStock,
			boolean droitConsommation, BigDecimal qteStock,
			BigDecimal prixAchat, BigDecimal prixVente, BigDecimal mtMarge,
			BigDecimal poidsBrut, BigDecimal poidsNet, String typeCodeBare,
			String description) {
		this.carticle = carticle;
		this.desArticle = desArticle;
		this.cunite = cunite;
		this.ctva = ctva;
		this.codeBarre = codeBarre;
		this.fodec = fodec;
		this.gererStock = gererStock;
		this.droitConsommation = droitConsommation;
		this.qteStock = qteStock;
		this.prixAchat = prixAchat;
		this.prixVente = prixVente;
		this.mtMarge = mtMarge;
		this.poidsBrut = poidsBrut;
		this.poidsNet = poidsNet;
		this.typeCodeBare = typeCodeBare;
		this.description = description;
	}
}