package tn.taktak.GestCommerciale_V1.entity;

// Generated 10 oct. 2015 15:25:00 by Hibernate Tools 3.4.0.CR1

/**
 * DetailBonAchatId generated by hbm2java
 */
public class DetailBonAchatId implements java.io.Serializable {

	private int nligne;
	private String cbonAchat;

	public DetailBonAchatId() {
	}

	public DetailBonAchatId(int nligne, String cbonAchat) {
		this.nligne = nligne;
		this.cbonAchat = cbonAchat;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getCbonAchat() {
		return this.cbonAchat;
	}

	public void setCbonAchat(String cbonAchat) {
		this.cbonAchat = cbonAchat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailBonAchatId))
			return false;
		DetailBonAchatId castOther = (DetailBonAchatId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getCbonAchat() == castOther.getCbonAchat()) || (this
						.getCbonAchat() != null
						&& castOther.getCbonAchat() != null && this
						.getCbonAchat().equals(castOther.getCbonAchat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37 * result
				+ (getCbonAchat() == null ? 0 : this.getCbonAchat().hashCode());
		return result;
	}

}
