package tn.taktak.GestCommerciale_V1.entity;

// Generated 10 oct. 2015 15:25:00 by Hibernate Tools 3.4.0.CR1

/**
 * DetailBonCaisseId generated by hbm2java
 */
public class DetailBonCaisseId implements java.io.Serializable {

	private int nligne;
	private String cbonCaisse;

	public DetailBonCaisseId() {
	}

	public DetailBonCaisseId(int nligne, String cbonCaisse) {
		this.nligne = nligne;
		this.cbonCaisse = cbonCaisse;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getCbonCaisse() {
		return this.cbonCaisse;
	}

	public void setCbonCaisse(String cbonCaisse) {
		this.cbonCaisse = cbonCaisse;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailBonCaisseId))
			return false;
		DetailBonCaisseId castOther = (DetailBonCaisseId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getCbonCaisse() == castOther.getCbonCaisse()) || (this
						.getCbonCaisse() != null
						&& castOther.getCbonCaisse() != null && this
						.getCbonCaisse().equals(castOther.getCbonCaisse())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37
				* result
				+ (getCbonCaisse() == null ? 0 : this.getCbonCaisse()
						.hashCode());
		return result;
	}

}
