package tn.taktak.GestCommerciale_V1.entity;

// Generated 10 oct. 2015 15:25:00 by Hibernate Tools 3.4.0.CR1

/**
 * DetailBonLivraisonId generated by hbm2java
 */
public class DetailBonLivraisonId implements java.io.Serializable {

	private int nligne;
	private String cbonLivraison;

	public DetailBonLivraisonId() {
	}

	public DetailBonLivraisonId(int nligne, String cbonLivraison) {
		this.nligne = nligne;
		this.cbonLivraison = cbonLivraison;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getCbonLivraison() {
		return this.cbonLivraison;
	}

	public void setCbonLivraison(String cbonLivraison) {
		this.cbonLivraison = cbonLivraison;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailBonLivraisonId))
			return false;
		DetailBonLivraisonId castOther = (DetailBonLivraisonId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getCbonLivraison() == castOther.getCbonLivraison()) || (this
						.getCbonLivraison() != null
						&& castOther.getCbonLivraison() != null && this
						.getCbonLivraison()
						.equals(castOther.getCbonLivraison())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37
				* result
				+ (getCbonLivraison() == null ? 0 : this.getCbonLivraison()
						.hashCode());
		return result;
	}

}
