package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * DetailInventaire generated by hbm2java
 */
public class DetailInventaire implements java.io.Serializable {

	private DetailInventaireId id;
	private String carticle;
	private String cunite;
	private BigDecimal qteTheorique;
	private BigDecimal qteReel;
	private BigDecimal ecart;
	private BigDecimal prixUnitaire;
	private BigDecimal totalPrixUnitaire;
	private String commentaire;

	public DetailInventaire() {
	}

	public DetailInventaire(DetailInventaireId id, String carticle,
			String cunite, BigDecimal qteTheorique, BigDecimal qteReel,
			BigDecimal ecart, BigDecimal prixUnitaire,
			BigDecimal totalPrixUnitaire, String commentaire) {
		this.id = id;
		this.carticle = carticle;
		this.cunite = cunite;
		this.qteTheorique = qteTheorique;
		this.qteReel = qteReel;
		this.ecart = ecart;
		this.prixUnitaire = prixUnitaire;
		this.totalPrixUnitaire = totalPrixUnitaire;
		this.commentaire = commentaire;
	}

	public DetailInventaireId getId() {
		return this.id;
	}

	public void setId(DetailInventaireId id) {
		this.id = id;
	}

	public String getCarticle() {
		return this.carticle;
	}

	public void setCarticle(String carticle) {
		this.carticle = carticle;
	}

	public String getCunite() {
		return this.cunite;
	}

	public void setCunite(String cunite) {
		this.cunite = cunite;
	}

	public BigDecimal getQteTheorique() {
		return this.qteTheorique;
	}

	public void setQteTheorique(BigDecimal qteTheorique) {
		this.qteTheorique = qteTheorique;
	}

	public BigDecimal getQteReel() {
		return this.qteReel;
	}

	public void setQteReel(BigDecimal qteReel) {
		this.qteReel = qteReel;
	}

	public BigDecimal getEcart() {
		return this.ecart;
	}

	public void setEcart(BigDecimal ecart) {
		this.ecart = ecart;
	}

	public BigDecimal getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(BigDecimal prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	public BigDecimal getTotalPrixUnitaire() {
		return this.totalPrixUnitaire;
	}

	public void setTotalPrixUnitaire(BigDecimal totalPrixUnitaire) {
		this.totalPrixUnitaire = totalPrixUnitaire;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

}
