package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

/**
 * DetailOrdrePaiementFournisseurId generated by hbm2java
 */
public class DetailOrdrePaiementFournisseurId implements java.io.Serializable {

	private int nligne;
	private String cordrePaiementFournisseur;

	public DetailOrdrePaiementFournisseurId() {
	}

	public DetailOrdrePaiementFournisseurId(int nligne,
			String cordrePaiementFournisseur) {
		this.nligne = nligne;
		this.cordrePaiementFournisseur = cordrePaiementFournisseur;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getCordrePaiementFournisseur() {
		return this.cordrePaiementFournisseur;
	}

	public void setCordrePaiementFournisseur(String cordrePaiementFournisseur) {
		this.cordrePaiementFournisseur = cordrePaiementFournisseur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailOrdrePaiementFournisseurId))
			return false;
		DetailOrdrePaiementFournisseurId castOther = (DetailOrdrePaiementFournisseurId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getCordrePaiementFournisseur() == castOther
						.getCordrePaiementFournisseur()) || (this
						.getCordrePaiementFournisseur() != null
						&& castOther.getCordrePaiementFournisseur() != null && this
						.getCordrePaiementFournisseur().equals(
								castOther.getCordrePaiementFournisseur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37
				* result
				+ (getCordrePaiementFournisseur() == null ? 0 : this
						.getCordrePaiementFournisseur().hashCode());
		return result;
	}

}
