package tn.taktak.GestCommerciale_V1.entity;

// Generated 10 oct. 2015 15:25:00 by Hibernate Tools 3.4.0.CR1

/**
 * DetailFactureClientId generated by hbm2java
 */
public class DetailFactureClientId implements java.io.Serializable {

	private int nligne;
	private String cfactureClient;

	public DetailFactureClientId() {
	}

	public DetailFactureClientId(int nligne, String cfactureClient) {
		this.nligne = nligne;
		this.cfactureClient = cfactureClient;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getCfactureClient() {
		return this.cfactureClient;
	}

	public void setCfactureClient(String cfactureClient) {
		this.cfactureClient = cfactureClient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailFactureClientId))
			return false;
		DetailFactureClientId castOther = (DetailFactureClientId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getCfactureClient() == castOther.getCfactureClient()) || (this
						.getCfactureClient() != null
						&& castOther.getCfactureClient() != null && this
						.getCfactureClient().equals(
								castOther.getCfactureClient())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37
				* result
				+ (getCfactureClient() == null ? 0 : this.getCfactureClient()
						.hashCode());
		return result;
	}

}
