package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

import lombok.Getter;
import lombok.Setter;

/**
 * DetailAvoirClient generated by hbm2java
 */
@Entity @IdClass(DetailAvoirClientId.class)
@Getter
@Setter
public class DetailAvoirClient {

	//private DetailAvoirClientId id;
	@Id
	private int nligne;
	@Id
	private String cavoirClient;
	private String carticle;
	private String ctva;
	private String cunite;
	private boolean droitConsommation;
	private BigDecimal tauxConsommation;
	private String desArticle;
	private BigDecimal quantiteConsommer;
	private BigDecimal prixRevientUnite;
	private BigDecimal tauxMarge;
	private BigDecimal mtUniteMarge;
	private BigDecimal prixUniteVente;
	private BigDecimal tauxRemise;
	private BigDecimal mtUniteRemise;
	private BigDecimal prixUniteHt;
	private BigDecimal tauxTva;
	private BigDecimal mtUniteTva;
	private BigDecimal mtUniteFodec;
	private BigDecimal prixUniteTtc;
	private BigDecimal mtTotalPrixVente;
	private BigDecimal mtTotalRemise;
	private BigDecimal mtTotalHt;
	private BigDecimal mtTotalTva;
	private BigDecimal mtTotalFodec;
	private BigDecimal mtTotalTtc;
	private BigDecimal mtTotalMarge;
	private BigDecimal poidsUniteBrut;
	private BigDecimal poidsUniteNet;
	private BigDecimal poidsTotalBrut;
	private BigDecimal poidsTotalNet;
	private String description;

	public DetailAvoirClient() {
	}

	public DetailAvoirClient(int nligne,String cavoirClient , String carticle,
			String ctva, String cuniteConsommer, boolean droitConsommation,
			BigDecimal tauxConsommation, String desArticle,
			BigDecimal quantiteConsommer, BigDecimal prixRevientUnite,
			BigDecimal tauxMarge, BigDecimal mtUniteMarge,
			BigDecimal prixUniteVente, BigDecimal tauxRemise,
			BigDecimal mtUniteRemise, BigDecimal prixUniteHt,
			BigDecimal tauxTva, BigDecimal mtUniteTva, BigDecimal mtUniteFodec,
			BigDecimal prixUniteTtc, BigDecimal mtTotalPrixVente,
			BigDecimal mtTotalRemise, BigDecimal mtTotalHt,
			BigDecimal mtTotalTva, BigDecimal mtTotalFodec,
			BigDecimal mtTotalTtc, BigDecimal mtTotalMarge) {
		this.nligne = nligne;
		this.cavoirClient = cavoirClient;
		this.carticle = carticle;
		this.ctva = ctva;
		this.cunite= cuniteConsommer;
		this.droitConsommation = droitConsommation;
		this.tauxConsommation = tauxConsommation;
		this.desArticle = desArticle;
		this.quantiteConsommer = quantiteConsommer;
		this.prixRevientUnite = prixRevientUnite;
		this.tauxMarge = tauxMarge;
		this.mtUniteMarge = mtUniteMarge;
		this.prixUniteVente = prixUniteVente;
		this.tauxRemise = tauxRemise;
		this.mtUniteRemise = mtUniteRemise;
		this.prixUniteHt = prixUniteHt;
		this.tauxTva = tauxTva;
		this.mtUniteTva = mtUniteTva;
		this.mtUniteFodec = mtUniteFodec;
		this.prixUniteTtc = prixUniteTtc;
		this.mtTotalPrixVente = mtTotalPrixVente;
		this.mtTotalRemise = mtTotalRemise;
		this.mtTotalHt = mtTotalHt;
		this.mtTotalTva = mtTotalTva;
		this.mtTotalFodec = mtTotalFodec;
		this.mtTotalTtc = mtTotalTtc;
		this.mtTotalMarge = mtTotalMarge;
	}

	public DetailAvoirClient(int nligne,String cavoirClient, String carticle,
			String ctva, String cuniteConsommer, boolean droitConsommation,
			BigDecimal tauxConsommation, String desArticle,
			BigDecimal quantiteConsommer, BigDecimal prixRevientUnite,
			BigDecimal tauxMarge, BigDecimal mtUniteMarge,
			BigDecimal prixUniteVente, BigDecimal tauxRemise,
			BigDecimal mtUniteRemise, BigDecimal prixUniteHt,
			BigDecimal tauxTva, BigDecimal mtUniteTva, BigDecimal mtUniteFodec,
			BigDecimal prixUniteTtc, BigDecimal mtTotalPrixVente,
			BigDecimal mtTotalRemise, BigDecimal mtTotalHt,
			BigDecimal mtTotalTva, BigDecimal mtTotalFodec,
			BigDecimal mtTotalTtc, BigDecimal mtTotalMarge,
			BigDecimal poidsUniteBrut, BigDecimal poidsUniteNet,
			BigDecimal poidsTotalBrut, BigDecimal poidsTotalNet,
			String description) {
		this.nligne = nligne;
		this.cavoirClient = cavoirClient;
		this.carticle = carticle;
		this.ctva = ctva;
		this.cunite= cuniteConsommer;
		this.droitConsommation = droitConsommation;
		this.tauxConsommation = tauxConsommation;
		this.desArticle = desArticle;
		this.quantiteConsommer = quantiteConsommer;
		this.prixRevientUnite = prixRevientUnite;
		this.tauxMarge = tauxMarge;
		this.mtUniteMarge = mtUniteMarge;
		this.prixUniteVente = prixUniteVente;
		this.tauxRemise = tauxRemise;
		this.mtUniteRemise = mtUniteRemise;
		this.prixUniteHt = prixUniteHt;
		this.tauxTva = tauxTva;
		this.mtUniteTva = mtUniteTva;
		this.mtUniteFodec = mtUniteFodec;
		this.prixUniteTtc = prixUniteTtc;
		this.mtTotalPrixVente = mtTotalPrixVente;
		this.mtTotalRemise = mtTotalRemise;
		this.mtTotalHt = mtTotalHt;
		this.mtTotalTva = mtTotalTva;
		this.mtTotalFodec = mtTotalFodec;
		this.mtTotalTtc = mtTotalTtc;
		this.mtTotalMarge = mtTotalMarge;
		this.poidsUniteBrut = poidsUniteBrut;
		this.poidsUniteNet = poidsUniteNet;
		this.poidsTotalBrut = poidsTotalBrut;
		this.poidsTotalNet = poidsTotalNet;
		this.description = description;
	}


}
