package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

/**
 * DetailInventaireId generated by hbm2java
 */
public class DetailInventaireId implements java.io.Serializable {

	private int nligne;
	private String ninventaire;

	public DetailInventaireId() {
	}

	public DetailInventaireId(int nligne, String ninventaire) {
		this.nligne = nligne;
		this.ninventaire = ninventaire;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getNinventaire() {
		return this.ninventaire;
	}

	public void setNinventaire(String ninventaire) {
		this.ninventaire = ninventaire;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailInventaireId))
			return false;
		DetailInventaireId castOther = (DetailInventaireId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getNinventaire() == castOther.getNinventaire()) || (this
						.getNinventaire() != null
						&& castOther.getNinventaire() != null && this
						.getNinventaire().equals(castOther.getNinventaire())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37
				* result
				+ (getNinventaire() == null ? 0 : this.getNinventaire()
						.hashCode());
		return result;
	}

}
