package tn.taktak.GestCommerciale_V1.entity;

import javax.persistence.Embeddable;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

// Generated 23 avr. 2015 18:41:00 by Hibernate Tools 3.4.0.CR1

/**
 * DetailDevisClientId generated by hbm2java
 */
//@Embeddable
public class DetailDevisClientId implements java.io.Serializable {

	
//	@ManyToOne(optional = false)
	private int nligne;
	
//	@ManyToOne(optional = false)
	private String cdevisClient;

	public DetailDevisClientId() {
	}

	public DetailDevisClientId(int nligne, String cdevisClient) {
		this.nligne = nligne;
		this.cdevisClient = cdevisClient;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getCdevisClient() {
		return this.cdevisClient;
	}

	public void setCdevisClient(String cdevisClient) {
		this.cdevisClient = cdevisClient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailDevisClientId))
			return false;
		DetailDevisClientId castOther = (DetailDevisClientId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getCdevisClient() == castOther.getCdevisClient()) || (this
						.getCdevisClient() != null
						&& castOther.getCdevisClient() != null && this
						.getCdevisClient().equals(castOther.getCdevisClient())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37
				* result
				+ (getCdevisClient() == null ? 0 : this.getCdevisClient()
						.hashCode());
		return result;
	}

}
