package tn.taktak.GestCommerciale_V1.entity;

// Generated 10 oct. 2015 15:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

import lombok.Getter;
import lombok.Setter;

/**
 * DetailBonAchat generated by hbm2java
 */
@Entity @IdClass(DetailBonAchatId.class)
@Getter
@Setter
public class DetailBonAchat  {

	//private DetailBonAchatId id;
	@Id
	private int nligne;
	@Id
	private String cbonAchat;
	private String ctva;
	private String carticle;
	private String cunite;
	private boolean droitConsommation;
	private BigDecimal tauxConsommation;
	private String desArticle;
	private BigDecimal quantiteConsommer;
	private BigDecimal prixUniteAchat;
	private BigDecimal tauxRemise;
	private BigDecimal mtUniteRemise;
	private BigDecimal prixUniteHt;
	private BigDecimal tauxTva;
	private BigDecimal mtUniteTva;
	private BigDecimal mtUniteFodec;
	private BigDecimal prixUniteTtc;
	private BigDecimal mtTotalPrixAchat;
	private BigDecimal mtTotalRemise;
	private BigDecimal mtTotalHt;
	private BigDecimal mtTotalTva;
	private BigDecimal mtTotalFodec;
	private BigDecimal mtTotalTtc;
	private BigDecimal poidsUniteBrut;
	private BigDecimal poidsUniteNet;
	private BigDecimal poidsTotalBrut;
	private BigDecimal poidsTotalNet;
	private String description;

	public DetailBonAchat() {
	}

	public DetailBonAchat(int nligne,String cbonAchat, String tva, String article,
			String unite, boolean droitConsommation,
			BigDecimal tauxConsommation, String desArticle,
			BigDecimal quantite, BigDecimal prixUniteAchat,
			BigDecimal tauxRemise, BigDecimal mtUniteRemise,
			BigDecimal prixUniteHt, BigDecimal tauxTva, BigDecimal mtUniteTva,
			BigDecimal mtUniteFodec, BigDecimal prixUniteTtc,
			BigDecimal mtTotalPrixAchat, BigDecimal mtTotalRemise,
			BigDecimal mtTotalHt, BigDecimal mtTotalTva,
			BigDecimal mtTotalFodec, BigDecimal mtTotalTtc) {
		this.nligne = nligne;
		this.cbonAchat = cbonAchat;
		this.ctva = tva;
		this.carticle = article;
		this.cunite = unite;
		this.droitConsommation = droitConsommation;
		this.tauxConsommation = tauxConsommation;
		this.desArticle = desArticle;
		this.quantiteConsommer = quantite;
		this.prixUniteAchat = prixUniteAchat;
		this.tauxRemise = tauxRemise;
		this.mtUniteRemise = mtUniteRemise;
		this.prixUniteHt = prixUniteHt;
		this.tauxTva = tauxTva;
		this.mtUniteTva = mtUniteTva;
		this.mtUniteFodec = mtUniteFodec;
		this.prixUniteTtc = prixUniteTtc;
		this.mtTotalPrixAchat = mtTotalPrixAchat;
		this.mtTotalRemise = mtTotalRemise;
		this.mtTotalHt = mtTotalHt;
		this.mtTotalTva = mtTotalTva;
		this.mtTotalFodec = mtTotalFodec;
		this.mtTotalTtc = mtTotalTtc;
	}

	public DetailBonAchat(int nligne,String cbonAchat, String tva, String article,
			String unite,  boolean droitConsommation,
			BigDecimal tauxConsommation, String desArticle,
			BigDecimal quantite, BigDecimal prixUniteAchat,
			BigDecimal tauxRemise, BigDecimal mtUniteRemise,
			BigDecimal prixUniteHt, BigDecimal tauxTva, BigDecimal mtUniteTva,
			BigDecimal mtUniteFodec, BigDecimal prixUniteTtc,
			BigDecimal mtTotalPrixAchat, BigDecimal mtTotalRemise,
			BigDecimal mtTotalHt, BigDecimal mtTotalTva,
			BigDecimal mtTotalFodec, BigDecimal mtTotalTtc,
			BigDecimal poidsUniteBrut, BigDecimal poidsUniteNet,
			BigDecimal poidsTotalBrut, BigDecimal poidsTotalNet,
			String description) {
		this.nligne = nligne;
		this.cbonAchat = cbonAchat;
		this.ctva = tva;
		this.carticle = article;
		this.cunite = unite;
		this.droitConsommation = droitConsommation;
		this.tauxConsommation = tauxConsommation;
		this.desArticle = desArticle;
		this.quantiteConsommer = quantite;
		this.prixUniteAchat = prixUniteAchat;
		this.tauxRemise = tauxRemise;
		this.mtUniteRemise = mtUniteRemise;
		this.prixUniteHt = prixUniteHt;
		this.tauxTva = tauxTva;
		this.mtUniteTva = mtUniteTva;
		this.mtUniteFodec = mtUniteFodec;
		this.prixUniteTtc = prixUniteTtc;
		this.mtTotalPrixAchat = mtTotalPrixAchat;
		this.mtTotalRemise = mtTotalRemise;
		this.mtTotalHt = mtTotalHt;
		this.mtTotalTva = mtTotalTva;
		this.mtTotalFodec = mtTotalFodec;
		this.mtTotalTtc = mtTotalTtc;
		this.poidsUniteBrut = poidsUniteBrut;
		this.poidsUniteNet = poidsUniteNet;
		this.poidsTotalBrut = poidsTotalBrut;
		this.poidsTotalNet = poidsTotalNet;
		this.description = description;
	}
	
	
	
	
	
	
	
	
//	public DetailBonAchat(DetailBonAchatId id, Tva tva, Article article,
//			Unite unite, BonAchat bonAchat, boolean droitConsommation,
//			BigDecimal tauxConsommation, String desArticle,
//			BigDecimal quantite, BigDecimal prixUniteAchat,
//			BigDecimal tauxRemise, BigDecimal mtUniteRemise,
//			BigDecimal prixUniteHt, BigDecimal tauxTva, BigDecimal mtUniteTva,
//			BigDecimal mtUniteFodec, BigDecimal prixUniteTtc,
//			BigDecimal mtTotalPrixAchat, BigDecimal mtTotalRemise,
//			BigDecimal mtTotalHt, BigDecimal mtTotalTva,
//			BigDecimal mtTotalFodec, BigDecimal mtTotalTtc) {
//		this.id = id;
//		this.tva = tva;
//		this.article = article;
//		this.unite = unite;
//		this.bonAchat = bonAchat;
//		this.droitConsommation = droitConsommation;
//		this.tauxConsommation = tauxConsommation;
//		this.desArticle = desArticle;
//		this.quantite = quantite;
//		this.prixUniteAchat = prixUniteAchat;
//		this.tauxRemise = tauxRemise;
//		this.mtUniteRemise = mtUniteRemise;
//		this.prixUniteHt = prixUniteHt;
//		this.tauxTva = tauxTva;
//		this.mtUniteTva = mtUniteTva;
//		this.mtUniteFodec = mtUniteFodec;
//		this.prixUniteTtc = prixUniteTtc;
//		this.mtTotalPrixAchat = mtTotalPrixAchat;
//		this.mtTotalRemise = mtTotalRemise;
//		this.mtTotalHt = mtTotalHt;
//		this.mtTotalTva = mtTotalTva;
//		this.mtTotalFodec = mtTotalFodec;
//		this.mtTotalTtc = mtTotalTtc;
//	}
//
//	public DetailBonAchat(DetailBonAchatId id, Tva tva, Article article,
//			Unite unite, BonAchat bonAchat, boolean droitConsommation,
//			BigDecimal tauxConsommation, String desArticle,
//			BigDecimal quantite, BigDecimal prixUniteAchat,
//			BigDecimal tauxRemise, BigDecimal mtUniteRemise,
//			BigDecimal prixUniteHt, BigDecimal tauxTva, BigDecimal mtUniteTva,
//			BigDecimal mtUniteFodec, BigDecimal prixUniteTtc,
//			BigDecimal mtTotalPrixAchat, BigDecimal mtTotalRemise,
//			BigDecimal mtTotalHt, BigDecimal mtTotalTva,
//			BigDecimal mtTotalFodec, BigDecimal mtTotalTtc,
//			BigDecimal poidsUniteBrut, BigDecimal poidsUniteNet,
//			BigDecimal poidsTotalBrut, BigDecimal poidsTotalNet,
//			String description) {
//		this.id = id;
//		this.tva = tva;
//		this.article = article;
//		this.unite = unite;
//		this.bonAchat = bonAchat;
//		this.droitConsommation = droitConsommation;
//		this.tauxConsommation = tauxConsommation;
//		this.desArticle = desArticle;
//		this.quantite = quantite;
//		this.prixUniteAchat = prixUniteAchat;
//		this.tauxRemise = tauxRemise;
//		this.mtUniteRemise = mtUniteRemise;
//		this.prixUniteHt = prixUniteHt;
//		this.tauxTva = tauxTva;
//		this.mtUniteTva = mtUniteTva;
//		this.mtUniteFodec = mtUniteFodec;
//		this.prixUniteTtc = prixUniteTtc;
//		this.mtTotalPrixAchat = mtTotalPrixAchat;
//		this.mtTotalRemise = mtTotalRemise;
//		this.mtTotalHt = mtTotalHt;
//		this.mtTotalTva = mtTotalTva;
//		this.mtTotalFodec = mtTotalFodec;
//		this.mtTotalTtc = mtTotalTtc;
//		this.poidsUniteBrut = poidsUniteBrut;
//		this.poidsUniteNet = poidsUniteNet;
//		this.poidsTotalBrut = poidsTotalBrut;
//		this.poidsTotalNet = poidsTotalNet;
//		this.description = description;
//	}

	

}
