package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

/**
 * DetailAvoirClientId generated by hbm2java
 */
public class DetailAvoirClientId implements java.io.Serializable {

	private int nligne;
	private String cavoirClient;

	public DetailAvoirClientId() {
	}

	public DetailAvoirClientId(int nligne, String cavoirClient) {
		this.nligne = nligne;
		this.cavoirClient = cavoirClient;
	}

	public int getNligne() {
		return this.nligne;
	}

	public void setNligne(int nligne) {
		this.nligne = nligne;
	}

	public String getCavoirClient() {
		return this.cavoirClient;
	}

	public void setCavoirClient(String cavoirClient) {
		this.cavoirClient = cavoirClient;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailAvoirClientId))
			return false;
		DetailAvoirClientId castOther = (DetailAvoirClientId) other;

		return (this.getNligne() == castOther.getNligne())
				&& ((this.getCavoirClient() == castOther.getCavoirClient()) || (this
						.getCavoirClient() != null
						&& castOther.getCavoirClient() != null && this
						.getCavoirClient().equals(castOther.getCavoirClient())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNligne();
		result = 37
				* result
				+ (getCavoirClient() == null ? 0 : this.getCavoirClient()
						.hashCode());
		return result;
	}

}
