package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;

import lombok.Getter;
import lombok.Setter;

/**
 * DetailOrdrePaiementFournisseur generated by hbm2java
 */
@Entity @IdClass(DetailOrdrePaiementFournisseurId.class)
@Getter
@Setter
public class DetailOrdrePaiementFournisseur {

	//private DetailOrdrePaiementFournisseurId id;
	@Id
	private int nligne;
	@Id
	private String cordrePaiementFournisseur;
	private String cordrePaiementFournisseurAcompte;
	private String cbonAchat;
	private BigDecimal mtSoldee;
	private BigDecimal mtRetiree;
	private BigDecimal mtNonSoldee;
	private String commentaire;

	public DetailOrdrePaiementFournisseur() {
	}

	public DetailOrdrePaiementFournisseur(int nligne, String cordrePaiementFournisseur,
			BigDecimal mtSoldee, BigDecimal mtRetiree, BigDecimal mtNonSoldee) {
		this.nligne=nligne;
		this.cordrePaiementFournisseur=cordrePaiementFournisseur;
		this.mtSoldee = mtSoldee;
		this.mtRetiree = mtRetiree;
		this.mtNonSoldee = mtNonSoldee;
	}

	public DetailOrdrePaiementFournisseur(int nligne, String cordrePaiementFournisseur,
			String cordrePaiementFournisseurAcompte, String cbonAchat,
			BigDecimal mtSoldee, BigDecimal mtRetiree, BigDecimal mtNonSoldee,
			String commentaire) {
		this.nligne=nligne;
		this.cordrePaiementFournisseur=cordrePaiementFournisseur;
		this.cordrePaiementFournisseurAcompte = cordrePaiementFournisseurAcompte;
		this.cbonAchat = cbonAchat;
		this.mtSoldee = mtSoldee;
		this.mtRetiree = mtRetiree;
		this.mtNonSoldee = mtNonSoldee;
		this.commentaire = commentaire;
	}
}