package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Inventaire generated by hbm2java
 */
public class Inventaire  {

	private String ninventaire;
	private String desInventaire;
	private Date dateCreation;
	private Date dateModification;
	private Date dateInventaire;
	private Date dateCloturation;
	private String etatInventaire;
	private BigDecimal totalPrixUnitare;
	private String observation;

	public Inventaire() {
	}

	public Inventaire(String ninventaire, Date dateCreation,
			Date dateModification, Date dateInventaire, Date dateCloturation,
			String etatInventaire, BigDecimal totalPrixUnitare) {
		this.ninventaire = ninventaire;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.dateInventaire = dateInventaire;
		this.dateCloturation = dateCloturation;
		this.etatInventaire = etatInventaire;
		this.totalPrixUnitare = totalPrixUnitare;
	}

	public Inventaire(String ninventaire, String desInventaire,
			Date dateCreation, Date dateModification, Date dateInventaire,
			Date dateCloturation, String etatInventaire,
			BigDecimal totalPrixUnitare, String observation) {
		this.ninventaire = ninventaire;
		this.desInventaire = desInventaire;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.dateInventaire = dateInventaire;
		this.dateCloturation = dateCloturation;
		this.etatInventaire = etatInventaire;
		this.totalPrixUnitare = totalPrixUnitare;
		this.observation = observation;
	}

	public String getNinventaire() {
		return this.ninventaire;
	}

	public void setNinventaire(String ninventaire) {
		this.ninventaire = ninventaire;
	}

	public String getDesInventaire() {
		return this.desInventaire;
	}

	public void setDesInventaire(String desInventaire) {
		this.desInventaire = desInventaire;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	public Date getDateInventaire() {
		return this.dateInventaire;
	}

	public void setDateInventaire(Date dateInventaire) {
		this.dateInventaire = dateInventaire;
	}

	public Date getDateCloturation() {
		return this.dateCloturation;
	}

	public void setDateCloturation(Date dateCloturation) {
		this.dateCloturation = dateCloturation;
	}

	public String getEtatInventaire() {
		return this.etatInventaire;
	}

	public void setEtatInventaire(String etatInventaire) {
		this.etatInventaire = etatInventaire;
	}

	public BigDecimal getTotalPrixUnitare() {
		return this.totalPrixUnitare;
	}

	public void setTotalPrixUnitare(BigDecimal totalPrixUnitare) {
		this.totalPrixUnitare = totalPrixUnitare;
	}

	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

}
