package tn.taktak.GestCommerciale_V1.entity;

import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Getter;
import lombok.Setter;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

/**
 * ModeReglement generated by hbm2java
 */

@Entity
@Getter
@Setter
public class ModeReglement  {

	@Id
	private String cmodeReglement;
	private String desModeReglement;

	public ModeReglement() {
	}

	public ModeReglement(String cmodeReglement, String desModeReglement) {
		this.cmodeReglement = cmodeReglement;
		this.desModeReglement = desModeReglement;
	}

}
