package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Getter;
import lombok.Setter;

/**
 * OrdrePaiementFournisseur generated by hbm2java
 */
@Entity
@Getter
@Setter
public class OrdrePaiementFournisseur {

	@Id
	private String cordrePaiementFournisseur;
	private String cfournisseur;
	private String cmodeReglement;
	private Date dateCreation;
	private Date dateModification;
	private Date dateOrdrePaiement;
	private String soldee;
	private String reference;
	private String textLibre;
	private String observation;
	private BigDecimal mtReglement;
	private BigDecimal mtEscompte;
	private BigDecimal mtVentiler;
	private BigDecimal mtFactures;
	private BigDecimal mtAvoirs;
	private BigDecimal mtDifferencesFacturesAvoirs;
	private BigDecimal mtSoldee;
	private BigDecimal mtNonSoldee;
	private boolean impaye;
	private boolean reglement;
	private boolean remboursement;
	private boolean genererAcompte;
	private boolean perteFournisseur;
	private boolean perteSociete;

	public OrdrePaiementFournisseur() {
	}

	public OrdrePaiementFournisseur(String cordrePaiementFournisseur,
			String cfournisseur, String cmodeReglement, Date dateCreation,
			Date dateModification, Date dateOrdrePaiement, String soldee,
			BigDecimal mtReglement, BigDecimal mtEscompte,
			BigDecimal mtVentiler, BigDecimal mtFactures, BigDecimal mtAvoirs,
			BigDecimal mtDifferencesFacturesAvoirs, BigDecimal mtSoldee,
			BigDecimal mtNonSoldee, boolean impaye, boolean reglement,
			boolean remboursement, boolean genererAcompte,
			boolean perteFournisseur, boolean perteSociete) {
		this.cordrePaiementFournisseur = cordrePaiementFournisseur;
		this.cfournisseur = cfournisseur;
		this.cmodeReglement = cmodeReglement;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.dateOrdrePaiement = dateOrdrePaiement;
		this.soldee = soldee;
		this.mtReglement = mtReglement;
		this.mtEscompte = mtEscompte;
		this.mtVentiler = mtVentiler;
		this.mtFactures = mtFactures;
		this.mtAvoirs = mtAvoirs;
		this.mtDifferencesFacturesAvoirs = mtDifferencesFacturesAvoirs;
		this.mtSoldee = mtSoldee;
		this.mtNonSoldee = mtNonSoldee;
		this.impaye = impaye;
		this.reglement = reglement;
		this.remboursement = remboursement;
		this.genererAcompte = genererAcompte;
		this.perteFournisseur = perteFournisseur;
		this.perteSociete = perteSociete;
	}

	public OrdrePaiementFournisseur(String cordrePaiementFournisseur,
			String cfournisseur, String cmodeReglement, Date dateCreation,
			Date dateModification, Date dateOrdrePaiement, String soldee,
			String reference, String textLibre, String observation,
			BigDecimal mtReglement, BigDecimal mtEscompte,
			BigDecimal mtVentiler, BigDecimal mtFactures, BigDecimal mtAvoirs,
			BigDecimal mtDifferencesFacturesAvoirs, BigDecimal mtSoldee,
			BigDecimal mtNonSoldee, boolean impaye, boolean reglement,
			boolean remboursement, boolean genererAcompte,
			boolean perteFournisseur, boolean perteSociete) {
		this.cordrePaiementFournisseur = cordrePaiementFournisseur;
		this.cfournisseur = cfournisseur;
		this.cmodeReglement = cmodeReglement;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.dateOrdrePaiement = dateOrdrePaiement;
		this.soldee = soldee;
		this.reference = reference;
		this.textLibre = textLibre;
		this.observation = observation;
		this.mtReglement = mtReglement;
		this.mtEscompte = mtEscompte;
		this.mtVentiler = mtVentiler;
		this.mtFactures = mtFactures;
		this.mtAvoirs = mtAvoirs;
		this.mtDifferencesFacturesAvoirs = mtDifferencesFacturesAvoirs;
		this.mtSoldee = mtSoldee;
		this.mtNonSoldee = mtNonSoldee;
		this.impaye = impaye;
		this.reglement = reglement;
		this.remboursement = remboursement;
		this.genererAcompte = genererAcompte;
		this.perteFournisseur = perteFournisseur;
		this.perteSociete = perteSociete;
	}
}