package tn.taktak.GestCommerciale_V1.entity;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

// Generated 23 avr. 2015 18:41:00 by Hibernate Tools 3.4.0.CR1

/**
 * RegimeTva generated by hbm2java
 */
@Entity
@Getter
@Setter
//@Table(name="RegimeTVA")
public class RegimeTva {

	@Id
	private String cregimeTva;
	private String desRegimeTva;

	public RegimeTva() {
	}

	public RegimeTva(String cregimeTva, String desRegimeTva) {
		this.cregimeTva = cregimeTva;
		this.desRegimeTva = desRegimeTva;
	}
}