package tn.taktak.GestCommerciale_V1.entity;

// Generated 10 oct. 2015 15:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Getter;
import lombok.Setter;

/**
 * Representant generated by hbm2java
 */

@Entity
@Getter
@Setter
public class Representant {

	@Id
	private String crepresentant;
	private String nom;
	private String prenom;
	private String desAdresse;
	private String codePostal;
	private String pays;
	private String ville;
	private String region;
	private String email;
	private String skype;
	private String tel;
	private String gsm1;
	private String gsm2;
	private String observation;
	private String login;
	private String motPasse;
	
	public Representant() {
	}

	public Representant(String crepresentant, String nom, String prenom) {
		this.crepresentant = crepresentant;
		this.nom = nom;
		this.prenom = prenom;
	}

	public Representant(String crepresentant, String nom, String prenom,
			String desAdresse, String codePostal, String pays, String ville,
			String region, String email, String skype, String tel, String gsm1,
			String gsm2, String observation, String login, String motPasse) {
		this.crepresentant = crepresentant;
		this.nom = nom;
		this.prenom = prenom;
		this.desAdresse = desAdresse;
		this.codePostal = codePostal;
		this.pays = pays;
		this.ville = ville;
		this.region = region;
		this.email = email;
		this.skype = skype;
		this.tel = tel;
		this.gsm1 = gsm1;
		this.gsm2 = gsm2;
		this.observation = observation;
		this.login = login;
		this.motPasse = motPasse;
	
	}

}
