package tn.taktak.GestCommerciale_V1.entity;

// Generated 10 oct. 2015 15:25:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;

import lombok.Getter;
import lombok.Setter;

/**
 * SessionCaisse generated by hbm2java
 */
@Entity
@Getter
@Setter
public class SessionCaisse  {

	@Id
	private String csessionCaisse;
	private String crepresentant;
	private Date dateDebut;
	private Date heureDebut;
	private Date dateFin;
	private Date heureFin;
	private boolean cloturee;
	private String observation;
	
	public SessionCaisse() {
	}

	public SessionCaisse(String csessionCaisse, String representant,
			Date dateDebut, Date heureDebut, Date dateFin, Date heureFin,
			boolean cloturee) {
		this.csessionCaisse = csessionCaisse;
		this.crepresentant = representant;
		this.dateDebut = dateDebut;
		this.heureDebut = heureDebut;
		this.dateFin = dateFin;
		this.heureFin = heureFin;
		this.cloturee = cloturee;
	}

	public SessionCaisse(String csessionCaisse, String representant,
			Date dateDebut, Date heureDebut, Date dateFin, Date heureFin,
			boolean cloturee, String observation) {
		this.csessionCaisse = csessionCaisse;
		this.crepresentant = representant;
		this.dateDebut = dateDebut;
		this.heureDebut = heureDebut;
		this.dateFin = dateFin;
		this.heureFin = heureFin;
		this.cloturee = cloturee;
		this.observation = observation;
		
	}

}
