package tn.taktak.GestCommerciale_V1.entity;

// Generated 23 avr. 2015 18:41:00 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * Tva generated by hbm2java
 */
@Entity
@Getter
@Setter
@Table(name="TVA")
public class Tva  {

	@Id
	private String ctva;
	private BigDecimal tauxTva;

	public Tva() {
	}

	public Tva(String ctva, BigDecimal tauxTva) {
		this.ctva = ctva;
		this.tauxTva = tauxTva;
	}
}