package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

/**
 * TvaregimeTvaId generated by hbm2java
 */
public class TvaregimeTvaId implements java.io.Serializable {

	private String ctva;
	private String cregimeTva;

	public TvaregimeTvaId() {
	}

	public TvaregimeTvaId(String ctva, String cregimeTva) {
		this.ctva = ctva;
		this.cregimeTva = cregimeTva;
	}

	public String getCtva() {
		return this.ctva;
	}

	public void setCtva(String ctva) {
		this.ctva = ctva;
	}

	public String getCregimeTva() {
		return this.cregimeTva;
	}

	public void setCregimeTva(String cregimeTva) {
		this.cregimeTva = cregimeTva;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TvaregimeTvaId))
			return false;
		TvaregimeTvaId castOther = (TvaregimeTvaId) other;

		return ((this.getCtva() == castOther.getCtva()) || (this.getCtva() != null
				&& castOther.getCtva() != null && this.getCtva().equals(
				castOther.getCtva())))
				&& ((this.getCregimeTva() == castOther.getCregimeTva()) || (this
						.getCregimeTva() != null
						&& castOther.getCregimeTva() != null && this
						.getCregimeTva().equals(castOther.getCregimeTva())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCtva() == null ? 0 : this.getCtva().hashCode());
		result = 37
				* result
				+ (getCregimeTva() == null ? 0 : this.getCregimeTva()
						.hashCode());
		return result;
	}

}
