package tn.taktak.GestCommerciale_V1.entity;

// Generated 3 nov. 2015 16:25:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TvaregimeTva generated by hbm2java
 */
public class TvaregimeTva implements java.io.Serializable {

	private TvaregimeTvaId id;
	private BigDecimal tauxTva;

	public TvaregimeTva() {
	}

	public TvaregimeTva(TvaregimeTvaId id, BigDecimal tauxTva) {
		this.id = id;
		this.tauxTva = tauxTva;
	}

	public TvaregimeTvaId getId() {
		return this.id;
	}

	public void setId(TvaregimeTvaId id) {
		this.id = id;
	}

	public BigDecimal getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(BigDecimal tauxTva) {
		this.tauxTva = tauxTva;
	}

}
